---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - name: myapp
    port: 8080
    targetPort: 8080
    nodePort: 32224
  selector:
    app: myapp
